import path from "node:path";
import { Glob } from "bun";
import { getBaseDir } from "./devRoute";

export async function routerGenerate() {
  const glob = new Glob("**/*.tsx");

  const cwd = process.cwd();
  const baseDir = getBaseDir()

  const routeDir = path.resolve(cwd, baseDir, "src/routes");

  const files = await Array.fromAsync(glob.scanSync({ cwd: routeDir }));
  const tsxFiles = files.filter((file) => file.endsWith(".tsx"));

  const imports: string[] = [];
  const routeEntries: string[] = [];

  tsxFiles.forEach((file, index) => {
    const normalizedFile = file.replace(/\\/g, "/");
    const cleanPath = normalizedFile.replace(/\.tsx$/, "");

    let routePath = "";
    if (cleanPath === "index") routePath = "/";
    else if (cleanPath.endsWith("/index"))
      routePath = `/${cleanPath.slice(0, -6)}`;
    else routePath = `/${cleanPath}`;

    const paramRoutePath = routePath.replace(/\/\$([^/]+)/g, "/:$1");
    const componentName = `Page_${index}`;
    const relativePath = `./routes/${normalizedFile}`;

    imports.push(
      `const ${componentName} = React.lazy(() => import('${relativePath}'));`,
    );
    routeEntries.push(`  '${paramRoutePath}': ${componentName},`);
  });

  const manifestCode = `
// This file is generated by Roge. Do not edit anything in this file!
import React from 'react';

${imports.join("\n")}

export const routes = {
${routeEntries.join("\n")}
} satisfies Record<string, React.LazyExoticComponent<React.ComponentType>>;
`.trim();

  const outputFilePath = path.resolve(cwd, baseDir, "src/.routerTree.ts");
  await Bun.write(outputFilePath, manifestCode);
}
