// This file is generated by Roge. Do not edit anything in this file!
import React from 'react';

const Page_0 = React.lazy(() => import('./routes/index.tsx'));

export const routes = {
  '/': Page_0,
} satisfies Record<string, React.LazyExoticComponent<React.ComponentType>>;